import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";
import Provider from "../components/Provider";
import { list } from "@/components/card/CardData";
import Cards from "@/components/card/Cards";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header />
          {children}
          <Cards list={list} />
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
